/*
Does lots of logging to disk via a durable task step (meaning very large logfiles for single steps)

Hammers durable-task, logging via remoting, 

*/ 
properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '100')), pipelineTriggers([])])

int randomFileSize = 1000;
for (int i = 0; i < 5; i++) {

    stage ("Stage Number $i") {
        for (int j = 0; j < 5; j++) {
            node {
                sh "for i in `seq 1 100`; do cat /dev/urandom | env LC_CTYPE=c tr -dc \'[:alpha:]\' | head -c $randomFileSize; done"
            }
        }
    }
}

