/*
Does lots of logging to disk via a durable task step (meaning very large logfiles for single steps)

Hammers durable-task, logging via remoting, 

*/ 
// properties [[$class: 'BuildDiscarderProperty', strategy: [$class: 'LogRotator', daysToKeepStr: '-1', numToKeepStr: '100']], [$class: 'ScannerJobProperty', doNotScan: false]]

int randomFileSize = 1000000;
for (int i = 0; i < 5; i++) {

    stage ("Stage $i") {
        for (int j = 0; j < 5; j++) {
            node {
                sh "for i in `seq 1 100`; do echo "Stage $i Loop $j"; cat /dev/urandom | env LC_CTYPE=c tr -dc \'[:alpha:]\' | fold -w $randomFileSize | head -n 1; done"
            }
        }
    }
}
