/*
parallel-plus-steps

Runs a bunch of echos in a parallelized series of...things
Slowed down to simulate some build steps etc
Also uses a node a bit.
*/

properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '100')), pipelineTriggers([])])

int branchCount = 20;
int stepsPerBranch = 5;

parallelSet = [:]

for (int i = 0; i < branchCount; i++) {
	echo "--> Creating ParallelSet[$i]"
	parallelSet["Branch $i"] = {
		for (int j = 0; j < stepsPerBranch; j++) {
			echo "--> Branch $i contains:"
		}
        node {
            sh 'sleep 10 && echo "Did some work on agent"'
        }
        for (int j = 0; j < stepsPerBranch; j++) {
            echo "    --> Echo j $j"
        }
	}
}
parallel parallelSet
sleep 5