pipeline {

    /* 
    If this is set to 
        agent { label 'master'} 
    it'll work fine.
    */ 
    agent any

    tools {
        maven 'maven'
        jdk 'jdk8'
    }
    
    options {
        buildDiscarder(logRotator(numToKeepStr: '20'))
    }

    stages {
        stage ('Build It') {
            steps {
                git (credentialsId: "git-ssh", url: "ssh://git@gitserver/git-server/repos/simple-maven-project-with-tests.git")
                echo '--> What is M2_HOME'
                sh 'echo "M2_HOME: ${M2_HOME}"'
                echo '--> What is JAVA_HOME'
                sh 'echo "JAVA_HOME: ${JAVA_HOME}"'
                echo '--> Where is java?'
                sh 'which java'
                echo '--> Build the thing'
                sh "mvn -X clean package"
            }
        }

    }

    post {
        always {
            echo "-- always -- step in post block."
        }
        success {
            echo "-- success -- step in post block -- HOORAY to things that work!"
            junit '**/target/surefire-reports/TEST-*.xml'
            archive 'target/*.jar'
        }
        failure {
            echo "-- failure -- step in post block -- BOO to things that don't work."
        }
    }
}