pipeline {

    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '20'))
    }

    stages {
        stage ('Build It') {
            steps {
                git (credentialsId: "git-ssh", url: "ssh://git@gitserver/git-server/repos/simple-maven-project-with-tests.git")
                echo '--> Build the thing'
                sh "mvn -X clean package"
            }
        }

    }

    post {
        always {
            echo "-- always -- step in post block."
            deleteDir()
        }
        success {
            echo "-- success -- step in post block -- HOORAY to things that work!"
            junit '**/target/surefire-reports/TEST-*.xml'
            archive 'target/*.jar'
        }
        failure {
            echo "-- failure -- step in post block -- BOO to things that don't work."
        }
    }
}