// Strains interleaved parallel logging with 15 parallel streams writing at 10 lines per second each

def notify(msg) {
    doNotify msg
    sh '''
        cat /dev/urandom | env LC_CTYPE=c tr -dc '[:alpha:]\n' | awk '{print $0; system("sleep .1");}'
    '''
}
def doNotify(msg) {
    sh "echo ${msg}"
}

def x = [:]
for (def i=0; i<15; i++) {
    x.put("branch${i}", { 
        node {
          notify("Hello")
        }
      }
    )
}

parallel(x)
