/*
A Jenkinsfile for our merge sort Groovy stuff.
This represents evaluating complex Groovy logic in normal pipeline code withoout using @NonCPS annotations
*/

library('sort-lib')

// Set the number of kept builds
properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '100')), pipelineTriggers([])])

// Create our arrays
int[] arrayToSort = null;
int[] sorted = null;
stage('Generate random data') {
    arrayToSort = Sorting.generateRandomArrayCPS(1000);
    echo 'Data generation done'
}

stage ('Sorting') {
    echo 'Starting sorting'
    sorted = Sorting.mergeSortCPS(arrayToSort)
    echo 'Sorting done!'
    echo Sorting.concatArrayToString(sorted)    
}