# https://github.com/m30m/docker-graphite-grafana
FROM alexmercer/graphite-grafana

# Port 2003 is graphite listener for plaintext (via carbon-cache here)
# Port 3000 is grafana
# Port 7002 is carbon-cache query from grafana