/*
A Jenkinsfile for our merge sort Groovy stuff.
This represents evaluating somewhat complex pure-groovy pipeline code.
Consider this a baseline against CPS and CPS+Echo versions.
*/

library('sort-lib')

// Set the number of kept builds
properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '100')), pipelineTriggers([])])

// Create our arrays
int[] arrayToSort = null;
int[] sorted = null;
stage('Generate random data') {
    arrayToSort = Sorting.generateRandomArray(1000);
    echo 'Data generation done'
}

stage ('Sorting') {
    echo 'Starting sorting'
    sorted = Sorting.mergeSort(arrayToSort)
    echo 'Sorting done!'
    echo Sorting.concatArrayToString(sorted)    
}