pipeline {
    agent any
    
    options {
        buildDiscarder(logRotator(numToKeepStr:'100'))
        }
    /*
    environment {
        VARIABLE = "SOMETHING"
    }
    */
    
    stages {
        
        stage ('echo \$PATH') {
            steps {
                sh 'echo $PATH'
                sleep 5
            }
        }
        
        stage ('Output of \'set\'') {
            steps {
                sh 'set'
                sleep 15
            }
        }
    } // end stages

    post {
        always {
            echo "Runs all the time."
        }
        success {
            echo "Whatever we did, it worked. Yay!"
        }
        failure {
            echo "Failed. Womp womp."
        }
    }
}