node {
    // TODO:
    // We need to add a withCredentials(whatever) thing to use the credential 
    // for the username `git`. That Credential is already on Jenkins, just have to 
    // write it into this Jenkinsfile the right way.
    withEnv(["JAVA_HOME=${ tool 'jdk8' }", "PATH+MAVEN=${tool 'maven'}/bin:${env.JAVA_HOME}/bin"]) {
    
    // def mvnHome = tool 'maven'
    // def java = tool 'jdk8'
    
    stage ('Sanity Check') {
        echo "where is maven"
        sh "which mvn"
        echo "where is java"
        sh "which java"
    }
    
    stage('Check out') { 
        // git 'https://github.com/jglick/simple-maven-project-with-tests.git'
        git 'ssh://git@gitserver/git-server/repos/simple-maven-project-with-tests.git'
    }
    
    stage('Build it') {
        sh "'${mvnHome}/bin/mvn' -Dmaven.test.failure.ignore clean package"
    }
    
    stage('Archive our results') {
        junit '**/target/surefire-reports/TEST-*.xml'
        archive 'target/*.jar'
    }
}

}