/*
Lightweight pipeline that should not put much stress on master and doesn't use agent
Useful for when we simply need a few jobs running but don't want to bog down
*/

properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '100')), pipelineTriggers([])])

echo 'just spinning here'
sleep 15