/*
Simple echo steps
*/

properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '100')), pipelineTriggers([])])

for (int i=0; i<10; i++) {
	stage ("Stage $i") {
		// Some echos.
		for (int j=0; j < 20; j++) {
			// Put in some logging.
            echo "Here goes echo number $j"
		}
	}
    sleep 1
}